#Separate the data with a colon like this:
#Name:Id:Meta:Price
ShopForm:
  Resources:
    - Cobblestone:4:0:1.3
    - Coal:263:0:3
    - Iron:265:0:14.9
    - Gold:266:0:19.3
    - Redstone:331:0:20.7
    - Diamonds:264:0:142
    - Emeralds:388:0:78.4
  Materials:
    - Oak Wood:17:0:5.3
    - Spruce Wood:17:1:5.3
    - Birch Wood:17:2:5.3
    - Dark Oak Wood:162:1:5.3
    - Acacia Wood:162:0:5.3
    - Jungle Wood:17:3:5.3
  Food:
    - Apple:260:0:1.3
    - Bread:297:0:1.3
    - Steak:364:0:1.3
  Special:
    - Beacon:138:0:10000
    - Golden Apple:322:0:250
    - Enchanted Golden Apple:466:1:3000

Command:
  Shop: "shop"
  ShopDescription: "Open an item shop"