#Separate the data with a colon like this:
#Name:NamespaceID:Meta:Price
#You can find namespace ids here: https://minecraft.gamepedia.com/Bedrock_Edition_data_value
ShopForm:
  Resources:
    - Cobblestone:cobblestone:0:1.3
    - Coal:coal:0:3
    - Iron:iron_ingot:0:14.9
    - Gold:gold_ingot:0:19.3
    - Redstone:redstone:0:20.7
    - Diamonds:diamond:0:142
    - Emeralds:emerald:0:78.4
  Materials:
    - Oak Wood:log:0:5.3
    - Spruce Wood:log:1:5.3
    - Birch Wood:log:2:5.3
    - Dark Oak Wood:log2:1:5.3
    - Acacia Wood:log2:0:5.3
    - Jungle Wood:log:3:5.3
  Food:
    - Apple:apple:0:1.3
    - Bread:bread:0:1.3
    - Steak:cooked_beef:0:1.3
    - Potato:potato:0:4.5
  Special:
    - Beacon:beacon:0:10000
    - Golden Apple:golden_apple:0:250
    - Enchanted Golden Apple:appleenchanted:1:3000

Command:
  Shop: "shop"
  ShopDescription: "Open an item shop"